#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MatApp.Resource", IsApplication=true)]

namespace MatApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BasicLinearLayoutStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BottomActionBarStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BottomBarButtonsStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditTextLinearLayoutStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int EditTextStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SideBarStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int TitleBarStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int VariableListLayoutStyle = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080035
			public const int CleanInput = 2131230773;
			
			// aapt resource value: 0x7f080033
			public const int Clear = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int Factorial = 2131230770;
			
			// aapt resource value: 0x7f08001a
			public const int ListLayout = 2131230746;
			
			// aapt resource value: 0x7f080028
			public const int Power = 2131230760;
			
			// aapt resource value: 0x7f08001c
			public const int ReportMessageView = 2131230748;
			
			// aapt resource value: 0x7f08002f
			public const int SemiColon = 2131230767;
			
			// aapt resource value: 0x7f080015
			public const int ShowConstant = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int ShowFunctions = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int ShowMatrixFunction = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int ShowPrefix = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int ShowVariables = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int ShowVectorFunction = 2131230743;
			
			// aapt resource value: 0x7f08000c
			public const int SideBarLayout = 2131230732;
			
			// aapt resource value: 0x7f080036
			public const int Solve = 2131230774;
			
			// aapt resource value: 0x7f080005
			public const int TitleLayout = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int VariableListLayout = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int basicTitleLayout = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int basicTitleLayout1 = 2131230724;
			
			// aapt resource value: 0x7f08001e
			public const int bottomActionBar = 2131230750;
			
			// aapt resource value: 0x7f080026
			public const int divide = 2131230758;
			
			// aapt resource value: 0x7f080002
			public const int editText1 = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int frameLayout1 = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int horizontalScrollView1 = 2131230751;
			
			// aapt resource value: 0x7f080006
			public const int imageButton1 = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout2 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout3 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout4 = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout5 = 2131230735;
			
			// aapt resource value: 0x7f080022
			public const int minus = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int multiply = 2131230756;
			
			// aapt resource value: 0x7f080020
			public const int plus = 2131230752;
			
			// aapt resource value: 0x7f08002c
			public const int smallBraketEnd = 2131230764;
			
			// aapt resource value: 0x7f08002a
			public const int smallBrakettStart = 2131230762;
			
			// aapt resource value: 0x7f080030
			public const int squareBraketEnd = 2131230768;
			
			// aapt resource value: 0x7f08002e
			public const int squareBraketStart = 2131230766;
			
			// aapt resource value: 0x7f080037
			public const int tableLayout1 = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int tableRow1 = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int tableRow2 = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int tableRow3 = 2131230778;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f08003b
			public const int textView10 = 2131230779;
			
			// aapt resource value: 0x7f080034
			public const int textView11 = 2131230772;
			
			// aapt resource value: 0x7f080021
			public const int textView2 = 2131230753;
			
			// aapt resource value: 0x7f080008
			public const int textView22 = 2131230728;
			
			// aapt resource value: 0x7f080018
			public const int textView24 = 2131230744;
			
			// aapt resource value: 0x7f08001d
			public const int textView28 = 2131230749;
			
			// aapt resource value: 0x7f080023
			public const int textView3 = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int textView4 = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int textView5 = 2131230759;
			
			// aapt resource value: 0x7f08002b
			public const int textView6 = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int textView7 = 2131230765;
			
			// aapt resource value: 0x7f080029
			public const int textView8 = 2131230761;
			
			// aapt resource value: 0x7f080031
			public const int textView81 = 2131230769;
			
			// aapt resource value: 0x7f080007
			public const int theInput = 2131230727;
			
			// aapt resource value: 0x7f08001b
			public const int theOutputList = 2131230747;
			
			// aapt resource value: 0x7f080010
			public const int theSideBarButtonView = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int theSideBarLinearLayout = 2131230737;
			
			// aapt resource value: 0x7f08003c
			public const int theVariableItem = 2131230780;
			
			// aapt resource value: 0x7f08000e
			public const int theVariableList = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int LayoutExperiment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MatAppTitleBar = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int theMatAppAdapter = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int theVariablelListAddapter = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
